/**
 *
 * $Id$
 */
package forsyde.validation;

import forsyde.Port;
import forsyde.Signal;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link forsyde.ProcessNetwork}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProcessNetworkValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validatePorts(EList<Port> value);
	boolean validateProcesses(EList<forsyde.Process> value);
	boolean validateSignals(EList<Signal> value);
}
