/**
 *
 * $Id$
 */
package forsyde.validation;

import forsyde.MoC;
import forsyde.Port;

/**
 * A sample validator interface for {@link forsyde.Signal}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SignalValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateMoc(MoC value);
	boolean validateDataType(String value);
	boolean validateSourceProcess(forsyde.Process value);
	boolean validateSourcePort(Port value);
	boolean validateTargetProcess(forsyde.Process value);
	boolean validateTargetPort(Port value);
}
