/**
 *
 * $Id$
 */
package forsyde.validation;

import forsyde.ProcessNetwork;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link forsyde.system}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface systemValidator {
	boolean validate();

	boolean validateProcessNetworks(EList<ProcessNetwork> value);

	boolean validateTop(ProcessNetwork value);
}
